export const RoutesData = {
    // pages
    // Presentation: { path: "/" },
    Signin: { path: "/" },
    DashboardOverview: { path: "/dashboard" },
    Transactions: { path: "/transactions" },
    Settings: { path: "/admin/settings" },
    Users: { path: "/admin/users" },
    Upgrade: { path: "/upgrade" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    Billing: { path: "/billing" },
    Invoice: { path: "/invoice" },
    Signup: { path: "/sign-up" },
    ForgotPassword: { path: "/forgot-password" },
    ResetPassword: { path: "/reset-password" },
    Lock: { path: "/lock" },
    NotFound: { path: "/404" },
    ServerError: { path: "/500" },

    Exercise: { path: "/admin/exercise" },
    Challenges: { path: "/admin/challenges" },
    Weeks: { path: "/admin/Weeks" },
    AddWeek: { path: "/admin/addweek" },
    WeekDays: { path: "/admin/weekdays" },
    AddWeekDays: { path: "/admin/addweekdays" },
    ChallengesExercise: { path: "/admin/challengesexercise" },
    AddChallengesExercise: { path: '/admin/addchallengesexercise' },
    CategoryExercise: { path: '/admin/categoryexercise' },
    Categories: { path: "/admin/category" },
    AddCategoryExercise: { path: "/admin/addcategoryexercise" },
    Discover: { path: "/admin/discover" },
    DiscoverExercise: { path: "/admin/discoverexercise" },
    AddDiscoverExercise: { path: "/admin/adddiscoverexercise" },
    QuickWorkout: { path: "/admin/quickworkout" },
    QuickWorkOutExercise: { path: "/admin/quickworkoutexercise" },
    AddQuickWorkOutExercise: { path: "/admin/addquickworkoutexercise" },
    Stretches: { path: "/admin/stretches" },
    StretchesExercise: { path: "/admin/StretchesExercise" },
    AddStretchesExercise: { path: "/admin/addstretchesexercise" },
    AddExercise: { path: "/admin/exercise/add" },
    AddChallenge: { path: "/admin/challenges/add" },
    AddCategory: { path: "/admin/category/add" },
    AddDiscover: { path: "/admin/discover/add" },
    AddQuickWorkout: { path: "/admin/workout/add" },
    AddStretches: { path: "/admin/stretches/add" },

    // docs
    DocsOverview: { path: "/documentation/overview" },
    DocsDownload: { path: "/documentation/download" },
    DocsQuickStart: { path: "/documentation/quick-start" },
    DocsLicense: { path: "/documentation/license" },
    DocsFolderStructure: { path: "/documentation/folder-structure" },
    DocsBuild: { path: "/documentation/build-tools" },
    DocsChangelog: { path: "/documentation/changelog" },

    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" }
};